#ifndef CONFIG_INS_CONFIG_SENSOR_ID_H_
#define CONFIG_INS_CONFIG_SENSOR_ID_H_

typedef enum
{
    FL_WHEEL_SPEED = 0U,
    FR_WHEEL_SPEED,
    RL_WHEEL_SPEED,
    RR_WHEEL_SPEED,

    INS_WHEEL_SPEED_SENSOR_COUNT,

    FL_SUSPENSION = INS_WHEEL_SPEED_SENSOR_COUNT,
    FR_SUSPENSION,
    RL_SUSPENSION,
    RR_SUSPENSION,

    INS_SUSPENSION_SENSOR_COUNT,

    INS_TOTAL_NUM_SENSORS = INS_SUSPENSION_SENSOR_COUNT
} ins_sensor_id_t;

#endif /*CONFIG_INS_CONFIG_SENSOR_ID_H_*/
