#ifndef PRM_CONFIG_PINOUT_H_
#define PRM_CONFIG_PINOUT_H_

#include "stm32h7xx_hal.h"

// 5V External 1
#define PRM_5V_EXTERNAL_1_EN_PORT GPIOI
#define PRM_5V_EXTERNAL_1_EN_PIN  GPIO_PIN_8

// 5V External 2
#define PRM_5V_EXTERNAL_2_EN_PORT GPIOI
#define PRM_5V_EXTERNAL_2_EN_PIN  GPIO_PIN_10

// 5V Internal 2
#define PRM_5V_INTERNAL_2_EN_PORT GPIOI
#define PRM_5V_INTERNAL_2_EN_PIN  GPIO_PIN_11

// 3V3 Internal 2
#define PRM_3V3_INTERNAL_2_EN_PORT GPIOE
#define PRM_3V3_INTERNAL_2_EN_PIN  GPIO_PIN_2

// 12V Internal
#define PRM_12V_INTERNAL_EN_PORT GPIOI
#define PRM_12V_INTERNAL_EN_PIN  GPIO_PIN_7

// 12V External 1
#define PRM_12V_EXTERNAL_1_EN_PORT GPIOD
#define PRM_12V_EXTERNAL_1_EN_PIN  GPIO_PIN_3

// 12V External 2
#define PRM_12V_EXTERNAL_2_EN_PORT GPIOD
#define PRM_12V_EXTERNAL_2_EN_PIN  GPIO_PIN_4


#endif /* PRM_CONFIG_PINOUT_H_ */